import { useState } from 'react'
import Icon from './Icons'
import { STAGES, stageStates, statusLabel } from './domain'
import { Results, Evidence } from './Analysis'
import { Modal } from './ui'

export function Workflow({ record, events, artifacts, t }) {
  const [detail, setDetail] = useState(null)
  const states = stageStates(events)
  const completed = Object.values(states).filter(state => state.status === 'completed').length
  const toolCalls = events.filter(e => e.type === 'tool.completed').length
  const cached = events.filter(e => e.type === 'tool.cached').length
  const duration = events.reduce((sum, e) => sum + (e.duration_ms || 0), 0)
  return <><div className="trace-heading"><div className="eyebrow">AGENT WORKFLOW</div><div className="trace-title"><h2>{record ? t('本次执行轨迹', 'Execution trace') : t('每一步，都有依据', 'A traceable workflow')}</h2><div className="progress-ring"><svg viewBox="0 0 48 48"><circle cx="24" cy="24" r="20" fill="none" stroke="#eaf1f4" strokeWidth="3"/><circle cx="24" cy="24" r="20" fill="none" stroke="#1b9d8d" strokeWidth="3" strokeDasharray={`${completed / 10 * 126} 126`} transform="rotate(-90 24 24)" strokeLinecap="round"/></svg><span>{completed}<small>/10</small></span></div></div><p>{record ? t('节点与工具状态来自本次实际执行。', 'Stages and tools reflect actual execution.') : t('研究开始后，在这里跟踪真实执行状态。', 'Track live execution after starting your study.')}</p></div>
    {!record ? <><div className="workflow-preview">{[['file','数据与财务审核','Data & review'],['layers','假设与现金流预测','Assumptions & forecast'],['chart','DCF 与相对估值','DCF & multiples'],['shield','敏感性与交叉验证','Sensitivity & validation']].map(([icon,zh,en],i)=><div className="phase" key={icon}><span className="phase-icon"><Icon name={icon}/></span><div><small>0{i+1}</small><b>{t(zh,en)}</b><span>{t('等待开始', 'Pending')}</span></div></div>)}</div><div className="info-note"><Icon name="tool"/><p>{t('工具调用、输入输出与运行耗时，会记录在研究轨迹中。', 'Tool calls, inputs, outputs and timing will be recorded here.')}</p></div></> : <><div className="execution-stats"><div><strong>{toolCalls}</strong><span>{t('工具完成', 'Tools done')}</span></div><div><strong>{cached}</strong><span>{t('结果复用', 'Cached')}</span></div><div><strong>{(duration / 1000).toFixed(1)}<small>s</small></strong><span>{t('工具耗时', 'Tool time')}</span></div></div><div className="stage-list">{STAGES.map(([id, zh, en], index) => {
      const state = states[id]
      return <details key={id} className={`stage-node ${state.status}`} open={state.status === 'running' || undefined}><summary><span className="stage-marker">{state.status === 'completed' ? <Icon name="check" size={14}/> : state.status === 'running' ? <span className="mini-spinner"/> : ['failed','waiting_review'].includes(state.status) ? '!' : String(index + 1).padStart(2, '0')}</span><b>{t(zh, en)}</b><span>{statusLabel(state.status, t)}</span><Icon name="chevron" size={13}/></summary><div className="stage-content">{state.tools.length ? state.tools.map(tool => <button className="tool-row" key={tool.key} onClick={() => setDetail({ event: tool, artifact: artifacts.find(a => a.artifact_id === tool.payload?.artifact_id) })}><Icon name="tool" size={15}/><div><b>{tool.tool}</b><small>{statusLabel(tool.status, t)}{tool.duration_ms != null ? ` · ${tool.duration_ms} ms` : ''}</small></div><Icon name="code" size={15}/></button>) : <p>{state.status === 'completed' ? t('阶段已完成；无独立工具调用或该方法未选用。', 'Stage complete; no separate tool call or method not selected.') : t('等待此阶段执行。', 'Waiting for this stage.')}</p>}</div></details>
    })}</div><p className="field-hint">{t('展开节点查看工具；点击工具可检查输入与输出。', 'Expand a stage, then select a tool to inspect inputs and outputs.')}</p></>}
    {detail && <Modal title={detail.event.tool || t('执行详情', 'Execution details')} onClose={() => setDetail(null)} className="wide-modal"><div className="detail-meta"><span>{statusLabel(detail.event.status, t)}</span><span>{detail.event.duration_ms == null ? '—' : `${detail.event.duration_ms} ms`}</span></div><h3>{t('输入参数', 'Input parameters')}</h3><pre>{JSON.stringify(detail.artifact?.inputs ?? detail.event.payload, null, 2)}</pre><h3>{t('输出结果', 'Output')}</h3><pre>{detail.artifact ? JSON.stringify(detail.artifact.output, null, 2) : detail.event.summary}</pre><p className="field-hint">{detail.event.type === 'tool.cached' ? t('此结果来自相同输入的已完成工具。', 'Reused from a completed tool with matching inputs.') : t('记录为实际调用数据，不包含模型内部思考过程。', 'Actual tool data; no private model reasoning is recorded.')}</p></Modal>}
  </>
}

export default function Inspector({ record, events, artifacts, t }) {
  const [tab, setTab] = useState('workflow')
  return <aside className="inspector-panel"><div className="inspector-tabs" role="tablist" aria-label={t('研究详情', 'Study details')}>{[['workflow','执行轨迹','Workflow'],['results','估值图谱','Valuation'],['evidence','数据依据','Evidence']].map(([id, zh, en]) => <button role="tab" aria-selected={tab === id} key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}>{t(zh,en)}</button>)}</div><div className="inspector-scroll" role="tabpanel">{tab === 'workflow' ? <Workflow {...{record, events, artifacts, t}}/> : tab === 'results' ? <Results record={record} t={t} compact/> : <Evidence {...{record, events, artifacts, t}}/>}</div></aside>
}
